IsaksMusic/Pages/Admin/Music/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using IsaksMusic.Data;
using IsaksMusic.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IsaksMusic.Pages.Admin.Music
{
    public class SongsModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConfiguration _configuration;

        public SongsModel(ApplicationDbContext applicationDbContext, IHostingEnvironment hostingEnvironment, IConfiguration configuration)
        {
            _applicationDbContext = applicationDbContext;
            _hostingEnvironment = hostingEnvironment;
            _configuration = configuration;
        }

        /* For uploading song */
        [BindProperty]
        public SongModel Song { get; set; }

        /* For displaying songs in table */
        public List<Song> SongList { get; set; }

        /* For displaying categories when uploading song */
        public List<SelectListItem> CategoryList { get; set; }

        [TempData]
        public string Message { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class SongModel
        {
            [Required(ErrorMessage = "A song needs a title")]
            public string Title { get; set; }

            [MaxLength(length: 150, ErrorMessage = "Description cannot exceed 150 characters.")]
            [Display(Name = "Description (optional)")]
            public string Description { get; set; }

            [Required(ErrorMessage = "Please specify minutes")]
            public byte Minutes { get; set; }

            [Required(ErrorMessage = "Please specify seconds")]
            public byte Seconds { get; set; }

            [Required(ErrorMessage = "Choose a file to upload")]
            public IFormFile MusicFile { get; set; }

            [Required(ErrorMessage = "Choose a category")]
            [Display(Name = "Music Categories (limit 2)")]
            public List<int> CategoryIds { get; set; }
        }

        public void OnGet()
        {
            /* List of songs */
            SongList = _applicationDbContext.Songs.Include(song => song.SongCategories)
                .ThenInclude(songCategories => songCategories.Category).OrderBy(song => song.Title).ToList();            

            /* Select List with categories */
            CategoryList = new List<SelectListItem>();

            /* Get categories from database */
            List<Category> categories = new List<Category>();
            categories = _applicationDbContext.Categories.ToList();

            /* Convert categories into select items */
            foreach (var category in categories)
            {
                CategoryList.Add(new SelectListItem { Value = category.Id.ToString(), Text = category.Name });
            }
        }

        public ActionResult OnGetDelete(int? id)
        {
            if (id != null)
            {
                var song = _applicationDbContext.Songs.Where(s => s.Id == id).SingleOrDefault();

                /* Remove entry from database */
                _applicationDbContext.Songs.Remove(song);
                _applicationDbContext.SaveChanges();

                /* Set full path to file */
                var fullPath = Path.Combine(_hostingEnvironment.WebRootPath, "music") + $@"\{song.FileName}";

                /* Remove file from server */
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            /* Full path to file */
            var fullPath = string.Empty;

            /* File name */
            var fileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    /* Get allowed file extensions */
                    IConfigurationSection myArraySection = _configuration.GetSection("AudioFileExtensions");
                    var extensionList = myArraySection.GetChildren().ToList().Select(c => c.Value).ToList();

                    /* Get file extension */
                    string fileExtension = Path.GetExtension(file.FileName);

                    /* Check file extension */
                    if (!extensionList.Contains(fileExtension))
                    {
                        ModelState.AddModelError("", "Invalid filetype.");
                    }

                    if (file.Length > 0 && ModelState.IsValid)
                    {
                        /* Get file name */
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        /* Set full path to file */
                        fullPath = Path.Combine(_hostingEnvironment.WebRootPath, "music") + $@"\{fileName}";

                        /* Upload to directory */
                        using (FileStream fs = System.IO.File.Create(fullPath))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }
            }

            /* If modelstate is valid */
            if (ModelState.IsValid)
            {
                TimeSpan songLength = new TimeSpan(0, Song.Minutes, Song.Seconds);
                long seconds = long.Parse(songLength.TotalSeconds.ToString());

                /* Create entry to database */
                Song song = new Song()
                {
                    Title = Song.Title,
                    Description = Song.Description,
                    Length = seconds,
                    UploadDate = DateTime.Now,
                    FileName = fileName
                };

                _applicationDbContext.Songs.Add(song);

                await _applicationDbContext.SaveChangesAsync();

                /* Get song ID */
                int songId = song.Id;

                /* Add song categories to database */
                foreach (var category in Song.CategoryIds)
                {
                    SongCategory songCategory = new SongCategory()
                    {
                        SongId = songId,
                        CategoryId = category
                    };

                    _applicationDbContext.SongCategories.Add(songCategory);
                }

                await _applicationDbContext.SaveChangesAsync();

                Message = "Song added";

                return RedirectToPage();
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                ErrorMessage = errors.FirstOrDefault().FirstOrDefault().ErrorMessage;
            }

            return RedirectToPage();

        }
    }
}

IsaksMusic/Pages/Music/Index.cshtml.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IsaksMusic.Data;
using IsaksMusic.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IsaksMusic.Pages.Music
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConfiguration _configuration;

        public IndexModel(ApplicationDbContext applicationDbContext, IHostingEnvironment hostingEnvironment, IConfiguration configuration)
        {
            _applicationDbContext = applicationDbContext;
            _hostingEnvironment = hostingEnvironment;
            _configuration = configuration;
        }

        public List<SongModel> SongList { get; set; }

        public ArrayList Playlist { get; set; }

        public bool Autoplay { get; set; }

        public IList<SelectListItem> CategoryList { get; set; }

        /// <summary>
        /// Get list of songs and categories
        /// </summary>
        /// <param name="autoplay"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetAsync(bool autoplay)
        {
            /* List of songs */
            var songs = await _applicationDbContext.Songs.Include(song => song.SongCategories)
                .ThenInclude(songCategories => songCategories.Category).OrderBy(song => song.Title).OrderBy(song => song.Order).ToListAsync();

            /* List of categories */

            SongList = new List<SongModel>();

            int count = 1;
            foreach (var song in songs)
            {
                SongList.Add(new SongModel
                {
                    SongId = song.Id,
                    PlaylistId = count,
                    Title = song.Title,
                    Categories = StringFormatter.GetCategoryString(song.SongCategories),
                    Description = song.Description,
                    Duration = StringFormatter.GetDurationFromSeconds(song.Length),
                    FilePath = "music/" + song.FileName
                });

                count++;
            }

            Playlist = new ArrayList();

            foreach (var song in SongList)
            {
                Playlist.Add(song.FilePath);
            }

            Autoplay = autoplay;

            CategoryList = new List<SelectListItem>();

            /* Get categories from database */
            List<Category> categories = new List<Category>();
            categories = _applicationDbContext.Categories.Where(c => _applicationDbContext.SongCategories.Select(sc => sc.CategoryId).Contains(c.Id)).ToList();

            /* Convert categories into select items */
            foreach (var category in categories)
            {
                CategoryList.Add(new SelectListItem { Text = category.Name });
            }

            return Page();
        }

        public class SongModel
        {
            public int SongId { get; set; }
            public int PlaylistId { get; set; }
            public string Title { get; set; }
            public string Categories { get; set; }
            public string Duration { get; set; }
            public string Description { get; set; }
            public string FilePath { get; set; }
        }
    }
}

IsaksMusic/Pages/Music/Track.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using IsaksMusic.Data;
using IsaksMusic.Models;

namespace IsaksMusic.Pages.Music
{
    public class TrackModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public TrackModel(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public SongModel Track { get; set; }

        /// <summary>
        /// Get track by ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task OnGetAsync(int? id)
        {
            if (id != null)
            {
                var song = await _applicationDbContext.Songs.Include(s => s.SongCategories)
                .ThenInclude(songCategories => songCategories.Category).OrderBy(s => s.Title).SingleOrDefaultAsync(m => m.Id == id);

                Track = new SongModel()
                {
                    Id = song.Id,
                    Title = song.Title,
                    Description = song.Description,
                    Categories = StringFormatter.GetCategoryString(song.SongCategories),
                    UploadDate = song.UploadDate.ToShortDateString(),
                    FilePath = "/music/" + song.FileName
                };
            }
        }

        /// <summary>
        /// Get random track
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetRandomAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var songs = await _applicationDbContext.Songs.Include(s => s.SongCategories).ThenInclude(sc => sc.Category).ToListAsync();

            songs.RemoveAll(s => s.Id == id);

            /* Get random track, but not the same */
            Random rand = new Random();
            int toSkip = rand.Next(0, songs.Count());
            var song = songs.Skip(toSkip).FirstOrDefault();

            Track = new SongModel()
            {
                Id = song.Id,
                Title = song.Title,
                Description = song.Description,
                Categories = StringFormatter.GetCategoryString(song.SongCategories),
                UploadDate = song.UploadDate.ToShortDateString(),
                FilePath = "/music/" + song.FileName
            };

            int songId = song.Id;
            Statistics statistics = new Statistics()
            {
                SongId = songId,
                PlayedDate = DateTime.Now.Date
            };

            await _applicationDbContext.Statistics.AddAsync(statistics);
            await _applicationDbContext.SaveChangesAsync();

            return Page();
        }

        public class SongModel
        {
            public int Id { get; set; }
            public string Title { get; set; }
            public string Categories { get; set; }
            public string Description { get; set; }
            public string FilePath { get; set; }
            public string UploadDate { get; set; }
        }
    }
}

IsaksMusic/Pages/Music/Index.cshtml
@page
@model IsaksMusic.Pages.Music.IndexModel
@{
    ViewData["Title"] = "Music";
    Layout = "~/Pages/_Layout.cshtml";
}

<!-- Mouseover tooltip -->
<div class="tooltip-track">00:00</div>

<div class="body-background">
    <div class="container" id="musicWrapper">
        <div class="row">
            <div class="col-xl-12" id="waveformContainer">
                <div id="waveformInner">
                    <div id="waveformHeader">
                        <h4 id="songPlayingTitle"></h4>
                        <label id="songPlayingCategories"></label>
                    </div>
                    <div id="waveform" class="text-center">
                        <p id="waveformMessage">Choose a track in the playlist below to play it.</p>
                    </div>
                    <div class="d-flex">
                        <div>
                            <span id="waveformCounter"></span>
                        </div>
                        <div class="ml-auto">
                            <span id="waveformDuration"></span>
                        </div>
                    </div>
                    <hr />
                    <div class="d-flex" id="waveformControls">
                        <div class="flex-group-item">
                            <a id="toggleShuffle" title="Shuffle" class="btn btn-dark mr-1" data-toggle="button" aria-pressed="false" autocomplete="off">
                                <i class="fas fa-random"></i>
                            </a>
                            <a id="toggleRepeat" title="Repeat" class="btn btn-dark" data-toggle="button" aria-pressed="false" autocomplete="off">
                                <i class="fas fa-redo"></i>
                            </a>
                        </div>
                        <div class="flex-group-item justify-content-center">
                            <a title="Play/Pause" id="playPauseBtn" class="btn btn-dark">
                                <i class="fas fa-play-circle fa-2x"></i>
                            </a>
                        </div>
                        <div class="flex-group-item flex-group-item-last">
                            <a id="togglePulse" title="Pulse" class="btn btn-dark mr-1 active" data-toggle="button" aria-pressed="true" autocomplete="off">
                                <i class="fas fa-heartbeat"></i>
                            </a>
                            <a id="volumeMenuButton" title="Volume" class="btn btn-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-volume-down"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-borderless dropdown-menu-right" id="volume-dropdown" aria-labelledby="volumeMenuButton">
                                <div id="volumeControl">
                                    <i class="fa fa-volume-off"></i>
                                    <div id="volumeSlider"></div>
                                    <i class="fa fa-volume-up"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12" id="songListContainer">
                <div id="songListHeader">
                    <h2 class="text-yellow">Songs</h2>
                    <p>Click a track to play it!</p>
                </div>
                <div id="songListControls" class="d-flex">
                    <div class="flex-group-item">
                        <a title="Toggle filters" class="btn btn-dark" data-toggle="collapse" id="songListFiltersBtn" href="#songListFilters" aria-controls="songListFilters"><i class="fas fas-mr fa-filter fa-sm"></i>Filter</a>
                    </div>
                    <div class="flex-group-item flex-group-item-last">
                        <a title="Clear song queue" class="btn btn-dark" data-toggle="tooltip" data-trigger="manual" id="clearQueueBtn" onclick="clearQueueList()"><i class="fas fas-mr fa-ban fa-sm"></i>Clear queue</a>
                    </div>
                </div>
                <div class="collapse" id="songListFilters">
                    <div id="songListFiltersInner">
                        <ul class="list-inline text-center">
                            @foreach (var category in Model.CategoryList)
                            {
                                <li class="list-inline-item"><input class="icheckbox mr-3" type="checkbox" id="@category.Text" />  @category.Text</li>
                            }
                        </ul>
                        <div class="text-center">
                            <a class="btn btn-success" id="filterChange" onclick="applyFilters()">Apply</a>
                            <a class="btn btn-dark" id="filterClear" onclick="clearFilters()">Clear</a>
                        </div>
                    </div>
                </div>
                <div id="musicTableContainer">
                    @if (Model.SongList.Count == 0)
                    {
                        <div class="text-center">
                            <p><strong>Unfortunately, there are no tracks available at this moment.</strong><br />Check in another time or contact me for a sample. </p>
                        </div>
                    }
                    else
                    {
                        <table class="table" id="musicTable">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Title</th>
                                    <th class="dismissable">Genre</th>
                                    <th>Duration</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var song in Model.SongList)
                                {
                                    <tr id="@song.PlaylistId" title="@song.Title">
                                        <td class="is-playing min pl-3"><i class="fas fa-volume-up fa-sm"></i></td>
                                        <td onclick="loadSong(@song.PlaylistId)">@song.Title</td>
                                        <td class="categoryColumn" onclick="loadSong(@song.PlaylistId)">@song.Categories</td>
                                        <td class="dismissable" onclick="loadSong(@song.PlaylistId)">@song.Duration</td>
                                        <td class="min">
                                            <div class="song-actions">
                                                <a id="actionDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-h"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="actionDropdownButton">
                                                    <a title="Queue" class="dropdown-item queue-btn" onclick="addToQueueList(@song.PlaylistId)"><i class="fas fa-fw mr-2 fa-plus-square"></i>Queue</a>
                                                    <a title="Go to track" class="dropdown-item" asp-page="./track" asp-route-id="@song.SongId"><i class="fas fa-fw mr-2 fa-arrow-circle-right"></i>Go to track</a>
                                                    <a title="Share" class="dropdown-item" onclick="shareTrack(@song.SongId)"><i class="fas fa-fw mr-2 fa-share-alt"></i>Share</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }

                </div>
                <div id="songListFooter">
                    <label class="text-muted">Please note that some of these tracks might be in an unfinished state.</label>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function () {

        playlist = @Html.Raw(Json.Serialize(Model.SongList));

        if ("@Model.Autoplay" === "True") {
            $('#playPauseBtn').trigger('click');
        }
    }
</script>

@section scripts
    {
    <script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.5/wavesurfer.min.js"></script>
    <script src="~/js/music-player.min.js" asp-append-version="true"></script>
}

IsaksMusic/Pages/Music/Track.cshtml
@page "{id:int}"
@model IsaksMusic.Pages.Music.TrackModel
@{
    ViewData["Title"] = Model.Track.Title;
}
<!-- Facebook Meta Tags -->
@section MetaSection {
    <meta property="og:title" content="@Model.Track.Title" />
    <meta property="og:type" content="music.song" />
    <meta property="og:image" content="https://isaksmusic.azurewebsites.net/images/bg-header.jpg" />
    <meta property="og:url" content="https://isaksmusic.azurewebsites.net/music/track/@Model.Track.Id" />
    <meta property="og:description" content="@Model.Track.Description" />
}

<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '1910375995659521',
            autoLogAppEvents: true,
            xfbml: true,
            version: 'v3.0'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) { return; }
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<!-- Mouseover tooltip -->
<div class="tooltip-track">00:00</div>

<div class="body-background">
    <div class="container" id="trackWrapper">
        <div class="mb-2">
            <a asp-page="/music/index"><i class="fas fas-mr fa-arrow-alt-circle-left"></i>Back to all music</a>
        </div>
        <div class="row">
            <div class="col-xl-12" id="trackWrapperInner">
                <div id="waveformContainer">
                    <div id="waveformInner">
                        <div id="waveformHeader">
                            <h4 id="songPlayingTitle">@Model.Track.Title</h4>
                            <label id="songPlayingCategories">@Model.Track.Categories</label>
                            <a id="randomTrack" data-toggle="tooltip" title="Random track" asp-page="./Track" asp-page-handler="Random" asp-route-id="@Model.Track.Id">
                                <img src="~/images/dice.svg" height="50" width="50" />
                            </a>
                        </div>
                        <div id="waveform" class="text-center">
                            <p id="waveformMessage">Loading track...</p>
                        </div>
                        <div class="d-flex">
                            <div>
                                <span id="waveformCounter"></span>
                            </div>
                            <div class="ml-auto">
                                <span id="waveformDuration"></span>
                            </div>
                        </div>
                        <hr />
                        <div class="d-flex" id="waveformControls">
                            <div class="flex-group-item">
                                <a id="toggleRepeat" title="Repeat" class="btn btn-dark" data-toggle="button" aria-pressed="false" autocomplete="off">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                            <div class="flex-group-item justify-content-center">
                                <a title="Play/Pause" id="playPauseBtn" class="btn btn-dark">
                                    <i class="fas fa-play-circle fa-2x"></i>
                                </a>
                            </div>
                            <div class="flex-group-item flex-group-item-last">
                                <a id="volumeMenuButton" title="Volume" class="btn btn-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-volume-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-borderless dropdown-menu-right" id="volume-dropdown" aria-labelledby="volumeMenuButton">
                                    <div id="volumeControl">
                                        <i class="fa fa-volume-off"></i>
                                        <div id="volumeSlider"></div>
                                        <i class="fa fa-volume-up"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <div id="trackContainer">
                            <div class="row">
                                <div class="col-sm-6 d-flex">
                                    <label class="text-yellow mr-2">Upload Date: </label>
                                    <p>@Model.Track.UploadDate</p>
                                </div>
                                <div class="col-sm-6 d-flex">
                                    <label class="text-yellow mr-2">Genre: </label>
                                    <p>@Model.Track.Categories</p>
                                </div>
                            </div>
                            <div>
                                <label class="text-yellow">Description</label>
                                <div id="trackDescription">
                                    <p class="collapse" id="collapseDescription">
                                        @Model.Track.Description
                                    </p>
                                    <a class="collapsed" id="collapseDescriptionBtn" data-toggle="collapse" href="#collapseDescription" aria-expanded="false" aria-controls="collapseDescription"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Community -->
                <div class="row" id="communityWrapper">
                    <div class="col-md-12">
                        <div id="communityContainer">
                            <div>
                                <div class="ml-2">
                                    <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fisaksmusic.azurewebsites.net%2Fmusic%2Ftrack%2F @Model.Track.Id &width=106&layout=button_count&action=like&size=small&show_faces=true&share=true&height=46&appId=1910375995659521"
                                            width="106"
                                            height="46"
                                            style="border:none;overflow:hidden"
                                            scrolling="no"
                                            frameborder="0"
                                            allowTransparency="true"
                                            allow="encrypted-media"></iframe>
                                </div>                                
                                <div class="fb-comments"
                                     data-href="https://isaksmusic.azurewebsites.net/music/track/@Model.Track.Id"
                                     data-width="100%"
                                     data-numposts="5"
                                     data-colorscheme="dark">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function () {

        filePath = "@Model.Track.FilePath";
        wavesurfer.load(filePath);
        addStatistics(@Model.Track.Id)
    }
</script>

@section scripts
    {
    <script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.5/wavesurfer.min.js"></script>
    <script src="~/js/track.min.js" asp-append-version="true"></script>
}