IsaksMusic/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IsaksMusic.Models
{
    public class Song
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime UploadDate { get; set; }

        [Required]
        public string FileName { get; set; }

        [Required]
        public long Length { get; set; }

        public int Order { get; set; }

        public ICollection<SongCategory> SongCategories { get; set; }
    }
}

IsaksMusic/Models/Statistics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IsaksMusic.Models
{
    public class Statistics
    {
        public int Id { get; set; }

        [Required]
        public int SongId { get; set; }

        public Song Song { get; set; }

        public DateTime PlayedDate { get; set; }
    }
}

IsaksMusic/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IsaksMusic.Data;
using IsaksMusic.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IsaksMusic.Controllers
{
    [Produces("application/json")]
    [Route("api/Statistics")]
    public class StatisticsController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public StatisticsController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        [HttpPost]
        public async Task AddTrackCountAsync(int? id)
        {
            if (id != null)
            {
                int songId = (int)id;
                Statistics statistics = new Statistics()
                {
                    SongId = songId,
                    PlayedDate = DateTime.Now.Date
                };

                await _applicationDbContext.Statistics.AddAsync(statistics);
                await _applicationDbContext.SaveChangesAsync();
            }
        }
    }
}

IsaksMusic/Pages/Admin/Categories.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using IsaksMusic.Data;
using IsaksMusic.Models;
using System.ComponentModel.DataAnnotations;

namespace IsaksMusic.Pages.Admin.Categories
{
    public class CategoriesModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public CategoriesModel(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        [TempData]
        public string Message { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        [BindProperty]
        public CategoryModel Category { get; set; }

        public IList<Category> Categories { get;set; }        

        /// <summary>
        /// Get categories ordered by song count
        /// </summary>
        /// <returns></returns>
        public async Task OnGetAsync()
        {
            /* Get categories and order by number of songs */
            Categories = await _applicationDbContext.Categories.Include(c => c.SongCategories).ToListAsync();
            Categories = Categories.OrderByDescending(c => c.SongCategories.Count()).ToList();
        }

        /// <summary>
        /// Add new category
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                Category category = new Category()
                {
                    Name = Category.Name
                };                

                _applicationDbContext.Categories.Add(category);

                await _applicationDbContext.SaveChangesAsync();

                Message = "Category added";
            }

            return RedirectToPage();
        }

        /// <summary>
        /// Delete a category
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetDelete(int? id)
        {
            if (id != null)
            {
                var category = _applicationDbContext.Categories.Where(c => c.Id == id).Include(c => c.SongCategories).SingleOrDefault();

                /* Check if category has any songs */
                if (category.SongCategories.Count() > 0)
                {
                    ErrorMessage = "Category could not be removed because one or several songs depend on it.";
                    return StatusCode(400);
                }

                _applicationDbContext.Categories.Remove(category);
                await _applicationDbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        /// <summary>
        /// Rename a category
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetEdit(int? id, string name)
        {
            if (id != null)
            {
                var category = _applicationDbContext.Categories.Where(c => c.Id == id).SingleOrDefault();

                /* Change category name */
                category.Name = name;
                await _applicationDbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public class CategoryModel
        {
            [MinLength(2, ErrorMessage = "The name must contain more than 2 characters.")]
            [Required(ErrorMessage = "A category needs a name")]
            public string Name { get; set; }
        }
    }
}

IsaksMusic/Pages/Admin/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IsaksMusic.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace IsaksMusic.Pages.Admin
{
    public class DashboardModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public DashboardModel(ApplicationDbContext applicationDbContext, IHostingEnvironment hostingEnvironment, UserManager<ApplicationUser> userManager)
        {
            _applicationDbContext = applicationDbContext;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
        }

        public bool UnusedCategories { get; set; }

        public bool NoFeaturedSong { get; set; }

        public List<string> MissingFiles { get; set; }

        public int NewsRead { get; set; }
        public int SongsPlayed { get; set; }
        public string TrendingSong { get; set; }

        /// <summary>
        /// Get notifications and warnings
        /// </summary>
        /// <returns></returns>
        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);

            /* Check for unused categories */
            var categories = await _applicationDbContext.Categories.Where(c => !_applicationDbContext.SongCategories.Select(sc => sc.CategoryId).Contains(c.Id)).ToListAsync();

            if (categories.Count > 0)
            {
                UnusedCategories = true;
            }

            /* Check for featured song */
            var featuredSong = await _applicationDbContext.FeaturedSongs.FirstOrDefaultAsync();

            if (featuredSong == null)
            {
                NoFeaturedSong = true;
            }

            /* Check for broken links */
            var SongList = await _applicationDbContext.Songs.ToListAsync();

            var fullPath = Path.Combine(_hostingEnvironment.WebRootPath, "music");

            MissingFiles = new List<string>();

            for (int i = 0; i < SongList.Count; i++)
            {
                if (!System.IO.File.Exists(fullPath + $@"\{SongList[i].FileName}"))
                {
                    MissingFiles.Add(SongList[i].FileName);
                }
            }

            /* Statistics */
            SongsPlayed = await _applicationDbContext.Statistics.CountAsync();
            NewsRead = await _applicationDbContext.NewsEntries.SumAsync(n => n.ReadCount);
            try
            {
                TrendingSong = _applicationDbContext.Statistics.
                    Include(s => s.Song).Where(s => s.PlayedDate >= DateTime.Today.AddDays(-14) && s.PlayedDate <= DateTime.Now).
                    GroupBy(s => s.Song.Title).Select(g => new
                    {
                        Title = g.Key,
                        Count = g.Distinct().Count()
                    }).OrderByDescending(s => s.Count).
                    FirstOrDefault().Title;
            }
            catch
            {
                TrendingSong = "-";
            }
        }

        public class UserModel
        {
            public string Email { get; set; }
            public string Username { get; set; }
        }
    }
}

IsaksMusic/Pages/Admin/Settings.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using IsaksMusic.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace IsaksMusic.Pages.Admin
{
    public class SettingsModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<PasswordModel> _logger;

        public SettingsModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<PasswordModel> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [TempData]
        public string Message { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        [BindProperty]
        public PasswordModel Password { get; set; }

        [BindProperty]
        public EmailModel Email { get; set; }

        [BindProperty]
        public UsernameModel Username { get; set; }

        /// <summary>
        /// Open settings page
        /// </summary>
        public void OnGet()
        {
            ErrorMessage = null;
        }

        /// <summary>
        /// Change password
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostPasswordAsync()
        {
            ModelState.Remove("Username");

            ModelState.Remove("Email");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, Password.OldPassword, Password.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                ErrorMessage = errors.FirstOrDefault().FirstOrDefault().ErrorMessage;

                return Page();
            }

            await _signInManager.SignInAsync(user, isPersistent: false);
            _logger.LogInformation("User changed their password successfully.");
            Message = "Your password has been changed.";
            ErrorMessage = null;

            return RedirectToPage();
        }

        /// <summary>
        /// Change email
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostEmailAsync()
        {
            ModelState.Remove("Username");

            ModelState.Remove("OldPassword");
            ModelState.Remove("NewPassword");
            ModelState.Remove("ConfirmPassword");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var setEmailResult = await _userManager.SetEmailAsync(user, Email.Email);
            if (!setEmailResult.Succeeded)
            {
                foreach (var error in setEmailResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                ErrorMessage = errors.FirstOrDefault().FirstOrDefault().ErrorMessage;

                return Page();
            }

            _logger.LogInformation("User changed their email successfully.");
            Message = "Your email has been changed.";
            ErrorMessage = null;

            return RedirectToPage();
        }

        /// <summary>
        /// Change username
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostUsernameAsync()
        {
            ModelState.Remove("Email");

            ModelState.Remove("OldPassword");
            ModelState.Remove("NewPassword");
            ModelState.Remove("ConfirmPassword");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var setUsernameResult = await _userManager.SetUserNameAsync(user, Username.Username);

            if (!setUsernameResult.Succeeded)
            {
                foreach (var error in setUsernameResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                ErrorMessage = errors.FirstOrDefault().FirstOrDefault().ErrorMessage;

                return Page();
            }

            await _signInManager.SignInAsync(user, isPersistent: false);
            _logger.LogInformation("User changed their username successfully.");
            Message = "Your username has been changed.";
            ErrorMessage = null;

            return RedirectToPage();
        }

        public class PasswordModel
        {
            [Required(ErrorMessage = "This field is required.")]
            [DataType(DataType.Password)]
            [Display(Name = "Current password")]
            public string OldPassword { get; set; }

            [Required (ErrorMessage = "This field is required.")]
            [StringLength(100, ErrorMessage = "The password must be between {2} and {1} characters long.", MinimumLength = 8)]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public class EmailModel
        {
            [Required(ErrorMessage = "This field is required.")]
            [DataType(DataType.EmailAddress, ErrorMessage = "Not a valid email address.")]
            public string Email { get; set; }
        }

        public class UsernameModel
        {
            [Required(ErrorMessage = "This field is required.")]
            [StringLength(20, ErrorMessage = "The username must be between {2} and {1} characters long.", MinimumLength = 4)]
            public string Username { get; set; }
        }
    }
}

IsaksMusic/Pages/Admin/Categories.cshtml
@page
@model IsaksMusic.Pages.Admin.Categories.CategoriesModel

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Pages/Admin/_AdminLayout.cshtml";
}

<!-- Show success message if any -->
@if (!string.IsNullOrEmpty(Model.Message))
{
    <script>
        window.onload = function () {

            ShowSuccessSnackbar("@Model.Message");
        }
    </script>
}

<div>
    <div class="d-flex align-items-center">
        <h3>Categories</h3>
        <div class="ml-auto">
            <a title="Add category" class="btn btn-success text-white" data-toggle="modal" data-target="#newCategoryModal">+ New</a>
        </div>
    </div>
    <hr />
    <p>Click a category to edit the name, then click outside to save it.<br />Click the <i class="fas fa-times-circle fa-sm text-danger"></i> icon to delete the category.</p>
    @if (Model.ErrorMessage != null)
    {
        <div class="alert alert-danger mt-3" role="alert">
            @Model.ErrorMessage
        </div>
    }
</div>
@if (Model.Categories == null || Model.Categories.Count == 0)
{
    <p class="text-center mt-4">Sorry, we couldn't find any categories in the database.</p>
}
else
{
    <div id="categoryList">

        <ul>
            @foreach (var category in Model.Categories)
            {
                <li class="category-list-item" id="category_@category.Id">
                    <span spellcheck="false" class="list-item-editable">@category.Name</span>
                    <a class="text-danger ml-2" data-toggle="tooltip" title="Delete" onclick="deleteCategory(@category.Id)">
                        <i class="fas fa-times-circle fa-sm"></i>
                    </a>
                </li>
            }
        </ul>
    </div>
}

<div class="modal fade" id="newCategoryModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-yellow">Add Category</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="songForm" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Category.Name"></label>
                        <input asp-for="Category.Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Category.Name"></span>
                    </div>
                    <div class="form-group text-center mb-0">
                        <input type="submit" class="btn btn-success" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

IsaksMusic/Pages/Admin/Dashboard.cshtml
@page
@model IsaksMusic.Pages.Admin.DashboardModel
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_AdminLayout";
}

<h3>Dashboard</h3>
<hr />
<div>
    @if (Model.MissingFiles.Count > 0)
    {
        <div class="alert alert-warning alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h6 class="alert-heading">Warnings<i class="fas fa-exclamation-triangle ml-2"></i></h6>
            <ul>
                @foreach (var file in Model.MissingFiles)
                {
                    <li>It appears to be a file missing: <strong>@file.ToString()</strong></li>
                }
            </ul>
        </div>
    }
    @if (Model.NoFeaturedSong || Model.UnusedCategories)
    {
        <div class="alert alert-info alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h6 class="alert-heading">Notifications<i class="fas fa-info-circle ml-2"></i></h6>
            <ul>
                @if (Model.NoFeaturedSong)
                {
                    <li>There is currently no <a class="alert-link" asp-page="/admin/songs">song</a> featured on the home page.</li>
                }
                @if (Model.UnusedCategories)
                {
                    <li>You have <a class="alert-link" asp-page="/admin/categories">categories</a> that are not being used.</li>
                }
            </ul>
        </div>
    }
    @if (Model.MissingFiles.Count == 0 && !Model.NoFeaturedSong && !Model.UnusedCategories)
    {
        <p>No messages.</p>
    }
    <div id="dashboardStatistics">
        <hr />
        <div class="row text-center">
            <div class="col-sm-4 mb-3">
                <div>
                    <h5 class="text-yellow">News read (all time)</h5>
                    <h5 class="text-white">@Model.NewsRead</h5>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div>
                    <h5 class="text-yellow">Songs played (all time)</h5>
                    <h5 class="text-white">@Model.SongsPlayed</h5>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div>
                    <h5 class="text-yellow">Trending song</h5>
                    <h5 class="text-white">@Model.TrendingSong</h5>
                </div>
            </div>
        </div>
    </div>
</div>

IsaksMusic/Pages/Admin/Settings.cshtml
@page
@model IsaksMusic.Pages.Admin.SettingsModel
@{
    ViewData["Title"] = "Settings";
    Layout = "~/Pages/Admin/_AdminLayout.cshtml";
}

<!-- Show success message if any -->
@if (!string.IsNullOrEmpty(Model.Message))
{
    <script>
        window.onload = function () {

            ShowSuccessSnackbar("@Model.Message");
        }
    </script>
}

<h3>Settings</h3>
<hr />
@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger mt-3" role="alert">
        @Model.ErrorMessage
    </div>
}
    <div id="settingsAccordion">
        <div class="card">
            <a class="collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <div class="card-header" id="changeUsernameHeader">
                    <i class="fas fas-mr fa-plus"></i>
                    Change username
                </div>
            </a>

            <div id="collapseOne" class="collapse" aria-labelledby="changeUsernameHeader" data-parent="#settingsAccordion">
                <div class="card-body">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label asp-for="Username.Username"></label>
                            <input asp-for="Username.Username" class="form-control" autocomplete="off" />
                            <span asp-validation-for="Username.Username" class="text-danger"></span>
                        </div>
                        <div>
                            <button asp-page-handler="Username" type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card">
            <a class="collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                <div class="card-header" id="changePasswordHeader">
                    <i class="fas fas-mr fa-plus"></i>
                    Change password
                </div>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="changePasswordHeader" data-parent="#settingsAccordion">
                <div class="card-body">
                    <form asp-page-handler="Password" method="post">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Password.OldPassword"></label>
                                    <input asp-for="Password.OldPassword" class="form-control" />
                                    <span asp-validation-for="Password.OldPassword" class="text-danger"></span>                                    
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password.NewPassword"></label>
                                    <a class="float-right info-circle">
                                        <i tabindex="0" data-toggle="popover" data-trigger="focus" title="Password policy" data-content="- At least one digit<br/>- At least one uppercase letter<br/>- At least 8 characters<br/>- At least 6 unique characters" data-html="true" class="fas fa-info-circle"></i>
                                    </a>
                                    <input asp-for="Password.NewPassword" class="form-control" />
                                    <span asp-validation-for="Password.NewPassword" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Password.ConfirmPassword"></label>
                                    <input asp-for="Password.ConfirmPassword" class="form-control" />
                                    <span asp-validation-for="Password.ConfirmPassword" class="text-danger"></span>
                                </div>
                                <div>
                                    <button asp-page-handler="Password" type="submit" class="btn btn-success m-auto d-block">Save</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card">
            <a class="collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                <div class="card-header" id="changeEmailHeader">
                    <i class="fas fas-mr fa-plus"></i>
                    Change email
                </div>
            </a>

            <div id="collapseThree" class="collapse" aria-labelledby="changeEmailHeader" data-parent="#settingsAccordion">
                <div class="card-body">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label asp-for="Email.Email"></label>
                            <input asp-for="Email.Email" class="form-control" autocomplete="off" />
                            <span asp-validation-for="Email.Email" class="text-danger"></span>
                        </div>
                        <div>
                            <button asp-page-handler="Email" type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

IsaksMusic/Pages/Admin/_AdminLayout.cshtml
@{
    Layout = "_Layout";
}

<div class="body-background">
    <div class="container">
        <div id="adminLayoutWrapper">
            <div class="wrapper-header">
                <div class="wrapper-header-left">
                    <span id="adminSidemenuCollapse" data-target="#adminSidemenu" data-toggle="collapse"><i class="fas fa-rotate fa-bars fa-lg"></i></span>
                </div>
                <h2 class="text-dark">Admin</h2>
            </div>
            <div class="wrapper-body">
                <div class="side-menu-collapse collapse in width show" id="adminSidemenu">
                    <div class="list-group border-0 text-md-left">
                        <a asp-page="/admin/dashboard" class="list-group-item d-inline-block" title="Dashboard"><i class="fas fa-tachometer-alt fa-fw fas-mr"></i><span class="d-none d-md-inline">Dashboard</span></a>
                        <a asp-page="/admin/songs" class="list-group-item d-inline-block" title="Songs"><i class="fas fa-music fa-fw fas-mr"></i><span class="d-none d-md-inline">Songs</span></a>
                        <a asp-page="/admin/categories" class="list-group-item d-inline-block" title="Categories"><i class="fas fa-th fa-fw fas-mr"></i><span class="d-none d-md-inline">Categories</span></a>
                        <a asp-page="/admin/news/index" class="list-group-item d-inline-block" title="News"><i class="fas fa-newspaper fa-fw fas-mr"></i><span class="d-none d-md-inline">News</span></a>
                        <a asp-page="/admin/statistics" class="list-group-item d-inline-block" title="Statistics"><i class="fas fa-chart-pie fa-fw fas-mr"></i><span class="d-none d-md-inline">Statistics</span></a>
                        <a asp-page="/admin/settings" class="list-group-item d-inline-block" title="Settings"><i class="fas fa-cog fa-fw fas-mr"></i><span class="d-none d-md-inline">Settings</span></a>
                    </div>
                </div>
                <div class="wrapper-content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqgrid/4.6.0/plugins/jquery.tablednd.js"></script>
    <script src="~/js/admin.min.js" asp-append-version="true"></script>
}